spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/${MYSQL_SCHEMA}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true